### ISSUE TITLE
sam 2 install failed "libcudnn.so.9: cannot open shared object file: No such file or directory" but libcudnn.so.9 is installed

### ISSUE THREAD

**Issue by loeweh** [facebookresearch/segment-anything-2#112]
Hi,

_**I get the following error**_

```
(venv) loewe@fedora:~/segment-anything-2$ pip install -e .
Obtaining file:///home/loewe/segment-anything-2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/home/loewe/segment-anything-2/venv/lib64/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/loewe/segment-anything-2/venv/lib64/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/loewe/segment-anything-2/venv/lib64/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-xsiqr1s8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-xsiqr1s8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-xsiqr1s8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xsiqr1s8/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/tmp/pip-build-env-xsiqr1s8/overlay/lib64/python3.10/site-packages/torch/__init__.py", line 290, in <module>
          from torch._C import *  # noqa: F403
      ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

_**but libcudnn.so.9 is installed**_

```
(venv) loewe@fedora:~/segment-anything-2$ find . -iname libcudnn\*
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_adv.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_cnn.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_engines_precompiled.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_engines_runtime_compiled.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_graph.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_heuristic.so.9
./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_ops.so.9
```
_**and**_ 

```
(venv) loewe@fedora:~/segment-anything-2$ python
Python 3.10.14 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
/home/loewe/segment-anything-2/venv/lib64/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
>>> print(torch.backends.cudnn.version())
90100
>>> 
```

```
(venv) loewe@fedora:~/segment-anything-2$ nvidia-smi
Fri Aug  2 17:03:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:09:00.0  On |                  N/A |
|  0%   55C    P8              29W / 350W |    214MiB / 24576MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4643      G   /usr/libexec/Xorg                            88MiB |
|    0   N/A  N/A      4887      G   /usr/bin/gnome-shell                         31MiB |
|    0   N/A  N/A      7394      G   ...seed-version=20240801-180145.014000       84MiB |
+---------------------------------------------------------------------------------------+
(venv) loewe@fedora:~/segment-anything-2$ 
```

any idea what I did wrong?

Best Regards

Heiko

**Comment by ronghanghu** [comment]
Hi, this seems to be a weird issue -- it seems that `libcudnn.so.9` is installed but cannot be loaded at runtime. Could you try adding the following
```
export LD_LIBRARY_PATH=./venv/lib/python3.10/site-packages/nvidia/cudnn/lib:${LD_LIBRARY_PATH}
```
or
```
export LD_PRELOAD=./venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn.so.9
````
before running SAM 2, and see if it resolves the issue?

**Comment by ronghanghu** [comment]
We have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

Closing this issue -- Please reopen if the solutions above doesn't solve the problem.
