### ISSUE TITLE
Invalid shape {} for image data

### ISSUE THREAD

**Issue by dat-rohit** [facebookresearch/segment-anything-2#150]
Hey,

I am trying to use SAM2 for video masklets. However, I run into this error:

`C:\Users\\Documents\SNU\sam2_gui\segment-anything-2\sam2\modeling\backbones\hieradet.py:72: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  x = F.scaled_dot_product_attention(
propagate in video: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:19<00:00,  1.02s/it]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\pt-cuda-env\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Documents\SNU\sam2_gui\GUI.py", line 74, in run_segmentation
    self.create_output_video(video_dir, frame_names, video_segments)
  File "C:\Users\Documents\SNU\sam2_gui\GUI.py", line 89, in create_output_video
    plt.imshow(mask, alpha=0.5, cmap='jet')
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\_api\deprecation.py", line 459, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 2652, in imshow
    __ret = gca().imshow(
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\_api\deprecation.py", line 459, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\axes\_axes.py", line 5481, in imshow
    im.set_data(X)
  File "C:\Users\AppData\Roaming\Python\Python310\site-packages\matplotlib\image.py", line 715, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape (1, 512, 512) for image data
Traceback (most recent call last):
  File "C:\Users\Documents\SNU\sam2_gui\GUI.py", line 100, in <module>
    root.mainloop()
  File "C:\Users\anaconda3\envs\pt-cuda-env\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)`
    

The keypoint is it says **TypeError: Invalid shape (1, 512, 512) for image data**

However, I checked and all my JPG frames are in the shape of (512, 512, 3) so I also don't understand the mismatch between the actual and the reported shapes.

Did anyone run into the same error? Any advise for me?

I thank you in advance!

**Comment by dat-rohit** [comment]
Figured it was not a SAM2 related problem but a matplotlib one, I was trying to plot the masks while being in a channel-first shape, which matplotlib doesn't allow.
