### ISSUE TITLE
Error when compiling model: RuntimeError: query: last dimension must be contiguous`

### ISSUE THREAD

**Issue by Caspeerrr** [facebookresearch/segment-anything-2#184]
Hi. When I try to compile the image encoder by setting compile_image_encoder to True I get the error below. Anyone knows how to fix this? Thanks!

Traceback (most recent call last):
    backbone_out = self.forward_image(image)
  File "/project/sam2/sam2/modeling/sam2_base.py", line 457, in forward_image
    backbone_out = self.image_encoder(img_batch)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/project/sam2/sam2/modeling/backbones/image_encoder.py", line 29, in forward
    def forward(self, sample: torch.Tensor):
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 3905, in forward
    return compiled_fn(full_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1482, in g
    return f(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 2533, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1506, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1594, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 374, in __call__
    return self.get_current_callable()(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 680, in run
    return compiled_fn(new_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 378, in deferred_cudagraphify
    fn, out = cudagraphify(model, inputs, new_static_input_idxs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 405, in cudagraphify
    return manager.add_function(
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 1921, in add_function
    return fn, fn(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 1741, in run
    out = self._run(new_inputs, function_id)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 1782, in _run
    return self.run_eager(new_inputs, function_id)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 1897, in run_eager
    return node.run(new_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/cudagraph_trees.py", line 603, in run
    out = self.wrapped_function.model(new_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 401, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_/dw/cdwpai66k6m4hspk7cuufbjdwvxuh7ogg4ij73j3rwdzfu3uz6ya.py", line 3540, in call
    buf57 = aten._scaled_dot_product_efficient_attention(reinterpret_tensor(buf56, (256, 2, 16, 96), (3072, 1536, 1, 16), 0), reinterpret_tensor(buf55, (256, 2, 64, 96), (36864, 96, 576, 1), 192), reinterpret_tensor(buf55, (256, 2, 64, 96), (36864, 96, 576, 1), 384), None, False)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: query: last dimension must be contiguous

**Comment by ronghanghu** [comment]
Hi, this might be due to different PyTorch versions (PyTorch has fixed a few bugs related to `torch.compile` in more recent versions). Could you try installing PyTorch 2.3.1 or PyTorch 2.4.0 and see if it resolves the error?
