### ISSUE TITLE
Failed to pip install --no-build-isolation -e .

### ISSUE THREAD

**Issue by zsz00** [facebookresearch/segment-anything-2#31]
```
Obtaining file:///home/zhangyong/codes/mot/segment-anything-2-main
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/setuptools/build_meta.py", line 453, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/home/zhangyong/miniconda3/envs/sam2/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch.utils.cpp_extension'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by bertaye** [comment]
Seems like pytorch is missing, if you didnt already installed it you can use the cool widget here: https://pytorch.org/get-started/locally/

**Comment by zsz00** [comment]
segment-anything-2-main$ pip list |grep torch
torch                    2.4.0
torchvision              0.19.0

**Comment by someshfengde** [comment]
not sure if it can help anyone but it's working fine over kaggle made a notebook about it. for now it's working on nvidia gpus available machines only. 

https://www.kaggle.com/somesh88/sam-2-large-demo

**Comment by fritol** [comment]
worked for me:

install torch nightly!
install CUDA 12.1
run the sam2 pip command

**Comment by warframeAlpha** [comment]
Got a different error with this command.
```(esds) E:\code\deep_learning\SAM2>pip install -e .
Obtaining file:///E:/code/deep_learning/SAM2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "E:\toolbox\miniconda\envs\esds\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\toolbox\miniconda\envs\esds\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\toolbox\miniconda\envs\esds\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\setuptools\build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])     
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires     
          self.run_setup()
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "<string>", line 51, in get_extensions
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension      
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths      
          paths.append(_join_cuda_home(lib_dir))
                       ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Endz\AppData\Local\Temp\pip-build-env-ambe048d\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home    
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your 
CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with 
pip.
```
OS: Windows 10
This env already has 
torch                     2.4.0+cu124
torchaudio                2.4.0+cu124
torchvision               0.19.0+cu124
numpy                     1.26.4

**Comment by ronghanghu** [comment]
Hi, we have added [`INSTALL.md`](https://github.com/facebookresearch/segment-anything-2/blob/main/INSTALL.md) as an installation FAQ.

@warframeAlpha  Regarding this error:

This usually happens because the installation step cannot find the CUDA toolkits (that contain the NVCC compiler) to build a custom CUDA kernel in SAM 2. Please install [CUDA toolkits](https://developer.nvidia.com/cuda-toolkit-archive) or the version that matches the CUDA version for your PyTorch installation. If the error persists after installing CUDA toolkits, you may explicitly specify `CUDA_HOME` via
```
export CUDA_HOME=/usr/local/cuda  # change to your CUDA toolkit path
```
and rerun the installation.

Also, you should make sure
```
python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'
```
print `(True, a directory with cuda)` to verify that the CUDA toolkits are correctly set up.
