### ISSUE TITLE
Run all solutions when install, still failed

### ISSUE THREAD

**Issue by XinrunXu** [facebookresearch/segment-anything-2#63]
## pip install --no-build-isolation -e .

    RuntimeError: Error compiling objects for extension
    [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building editable for SAM-2
    Failed to build SAM-2
    ERROR: Could not build wheels for SAM-2, which is required to install pyproject.toml-based projects

## python setup.py build_ext --inplace 
    (sam2) C:\Users\PS\Desktop\segment-anything-2>python setup.py build_ext --inplace 
    CUDA_HOME in setup.py: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
    running build_ext
    C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py:384: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'sam2._C' extension
    Emitting ninja build file C:\Users\PS\Desktop\segment-anything-2\build\temp.win-amd64-cpython-310\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\PS\Desktop\segment-anything-2\build\temp.win-amd64-cpython-310\Release\sam2/csrc/connected_components.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\TH -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IC:\Users\PS\.conda\envs\sam2\include -IC:\Users\PS\.conda\envs\sam2\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\PS\Desktop\segment-anything-2\sam2\csrc\connected_components.cu -o C:\Users\PS\Desktop\segment-anything-2\build\temp.win-amd64-cpython-310\Release\sam2/csrc/connected_components.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=sm_80
    FAILED: C:/Users/PS/Desktop/segment-anything-2/build/temp.win-amd64-cpython-310/Release/sam2/csrc/connected_components.obj
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\PS\Desktop\segment-anything-2\build\temp.win-amd64-cpython-310\Release\sam2/csrc/connected_components.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\TH -IC:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IC:\Users\PS\.conda\envs\sam2\include -IC:\Users\PS\.conda\envs\sam2\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\PS\Desktop\segment-anything-2\sam2\csrc\connected_components.cu -o C:\Users\PS\Desktop\segment-anything-2\build\temp.win-amd64-cpython-310\Release\sam2/csrc/connected_components.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=sm_80
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
    connected_components.cu
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
        subprocess.run(
      File "C:\Users\PS\.conda\envs\sam2\lib\subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Users\PS\Desktop\segment-anything-2\setup.py", line 68, in <module>
        setup(
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\__init__.py", line 104, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
        return run_commands(dist)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
        dist.run_commands()
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\dist.py", line 967, in run_command
        super().run_command(command)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\command\build_ext.py", line 91, in run
        _build_ext.run(self)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
        self.build_extensions()
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
        objects = self.compiler.compile(
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "C:\Users\PS\.conda\envs\sam2\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension

**Comment by XinrunXu** [comment]
already run this line before
    pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121 --index-url https://download.pytorch.org/whl/cu121

**Comment by XinrunXu** [comment]
pip list
Package           Version
----------------- ------------
filelock          3.13.1
fsspec            2024.2.0
intel-openmp      2021.4.0
Jinja2            3.1.3
MarkupSafe        2.1.5
mkl               2021.4.0
mpmath            1.3.0
networkx          3.2.1
numpy             1.26.3
pillow            10.2.0
pip               24.0
setuptools        69.5.1
sympy             1.12
tbb               2021.11.0
torch             2.3.1+cu121
torchaudio        2.3.1+cu121
torchvision       0.18.1+cu121
typing_extensions 4.9.0
wheel             0.43.0

**Comment by XinrunXu** [comment]
Torch version: 2.3.1+cu121
CUDA available: True
CUDA version: 12.1
Number of CUDA devices: 1
CUDA device name: NVIDIA GeForce RTX 4090
Device properties: _CudaDeviceProperties(name='NVIDIA GeForce RTX 4090', major=8, minor=9, total_memory=24563MB, multi_processor_count=128)

**Comment by fritol** [comment]
worked for me:

install torch nightly!
install CUDA 12.1
run the sam2 pip command

**Comment by XinrunXu** [comment]
> worked for me:
> 
> install torch nightly! install CUDA 12.1 run the sam2 pip command

failed because ImportError: cannot import name '_C' from 'sam2' (c:\Users\PS\Desktop\segment-anything-2\sam2\__init__.py)

**Comment by ronghanghu** [comment]
@XinrunXu the issue you're facing is likely due to the line
> unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.

in your error log. It suggested that your local compiler doesn't match the one required for the `nvcc` command in CUDA toolkit. You may refer to https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/ to use an `nvcc`-compatible compiler. It looks like you're using Windows and WSL (Windows Subsystem for Linux) could be an alternative solution
